=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/input_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (Tue, 21 Oct 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<xsd:schema targetNamespace="http://www.hive.pt"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.hive.pt">
    <xsd:complexType name="tables">
		<xsd:sequence>
			<xsd:element name="table" type="table" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="table">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1"
				minOccurs="1" />
			<xsd:element name="internal_entity" type="xsd:string"
				maxOccurs="1" minOccurs="1" />
            <xsd:element name="primary_key" type="primary_key" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="foreign_keys" type="foreign_keys" maxOccurs="1" minOccurs="0"></xsd:element>
            <xsd:element name="columns" type="columns" maxOccurs="1" minOccurs="1" />
            <xsd:element name="handlers" type="handlers" maxOccurs="1" minOccurs="0" />
        </xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="primary_key">
		<xsd:sequence>
			<xsd:element name="primary_key_column" type="xsd:string" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="foreign_keys">
		<xsd:sequence>
			<xsd:element name="foreign_key" type="foreign_key" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="foreign_key">
		<xsd:sequence>
            <xsd:element name="foreign_key_columns" type="foreign_key_columns" maxOccurs="1" minOccurs="1" />
            <xsd:element name="foreign_table" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="columns">
		<xsd:sequence>
			<xsd:element name="column" type="column" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="column">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="internal_attribute" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="internal_entity" type="internal_entity" maxOccurs="1" minOccurs="0" />
			<xsd:element name="handlers" type="handlers" maxOccurs="1" minOccurs="0" />
			<xsd:element name="primary_key" type="xsd:boolean" maxOccurs="1" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="handlers">
		<xsd:sequence>
			<xsd:element name="handler" type="handler" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="handler">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="input_configuration">
		<xsd:sequence>
			<xsd:element name="tables" type="tables" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="internal_entity">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:integer" maxOccurs="1" minOccurs="1" />
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="input_configuration" type="input_configuration" />

	<xsd:complexType name="foreign_key_columns">
		<xsd:sequence>
			<xsd:element name="foreign_key_column" type="xsd:string" maxOccurs="unbounded" minOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/xml/produtos.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = SimÃ£o Rio <srio@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- produtos -->
			<name>produtos</name>
			<internal_entity>product</internal_entity>
			<primary_key>
				<primary_key_column>codigo</primary_key_column>
			</primary_key>
			
			<foreign_keys>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>tipopro</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>tipoprod</foreign_table>
				</foreign_key>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>tipopeca</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>tipopeca</foreign_table>
				</foreign_key>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>estilo</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>estilo</foreign_table>
				</foreign_key>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>forneced</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>forneced</foreign_table>
				</foreign_key>
			</foreign_keys>
			
			<handlers>
				<handler>
					<name>row_handler_feitio_to_design_cost</name>
				</handler>
				<handler>
					<name>row_handler_margin_calculation_type</name>
				</handler>
				<handler>
					<name>row_handler_margin_calculation</name>
				</handler>
			</handlers>
			
			<columns>
				<column> <!-- codigo -->
					<name>codigo</name>
					<internal_attribute>company_product_code</internal_attribute>
				</column>
				
				<column> <!-- descricao -->
					<name>descricao</name>
					<internal_attribute>name</internal_attribute>
				</column>
				
				<column> <!-- tipopro -->
					<name>tipopro</name>
					<internal_attribute>parent_nodes[?].parent_nodes[?]</internal_attribute>
				</column>
				
				<column> <!-- tipopeca -->
					<name>tipopeca</name>
					<internal_attribute>parent_nodes[?]</internal_attribute>
				</column>
				
				<column> <!-- estilo -->
					<name>estilo</name>
					<internal_attribute>parent_nodes[?]</internal_attribute>
				</column>
				
				<column> <!-- forneced -->
					<name>forneced</name>
					<internal_attribute>commercialization_suppliers[0]</internal_attribute>
				</column>
				
				<column> <!-- consigna-->
					<name>consigna</name>
					<internal_attribute>consignable[0]</internal_attribute>
				</column>
				
				<column> <!-- stockmin -->
					<name>stockmin</name>
					<internal_attribute>min_stock</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>merchandise_contactable_organizational_hierarchy_tree_node</name>
					</internal_entity>
				</column>
				
				<column> <!-- stock -->
					<name>stock</name>
					<internal_attribute>stock_on_hand</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>merchandise_contactable_organizational_hierarchy_tree_node</name>
					</internal_entity>
				</column>
				
				<column> <!-- pesounit -->
					<name>pesounit</name>
					<internal_attribute>weight</internal_attribute>
				</column>
				
				<column> <!-- feitio -->
					<name>feitio</name>
					<internal_attribute>design_cost</internal_attribute>
				</column>
				
				<column> <!-- tiplgp -->
					<name>tiplgp</name>
					<internal_attribute>lixo_1</internal_attribute>
				</column>
				
	
				
				<column> <!-- anulado -->
					<name>anulado</name>
					<internal_attribute>status</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_diamante_anulado_to_hive_status</name>
						</handler>
					</handlers>
				</column>
			</columns>
		</table>
	</tables>
</input_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/xml/lojas.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = SimÃ£o Rio <srio@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- lojas -->
			<name>lojas</name>
			<internal_entity>store</internal_entity>
			<primary_key>
				<primary_key_column>codigo</primary_key_column>
			</primary_key>			
			
			<columns>
				<column> <!-- codigo -->
					<name>codigo</name>
					<internal_attribute>id</internal_attribute>
				</column>
				
				<column> <!-- descricao -->
					<name>descricao</name>
					<internal_attribute>name</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				
				<column> <!-- email -->
					<name>email</name>
					<internal_attribute>email</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>contact_information</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- telefone -->
					<name>telefone</name>
					<internal_attribute>phone_number</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- fax -->
					<name>fax</name>
					<internal_attribute>fax_number</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				
				<column> <!-- morada -->
					<name>morada</name>
					<internal_attribute>name</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- local -->
					<name>local</name>
					<internal_attribute>zip_code_name</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
			</columns>
		</table>
	</tables>
</input_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/xml/empresas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = SimÃ£o Rio <srio@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- empresas -->
			<name>empresas</name>
			<internal_entity>system_company</internal_entity>
			<primary_key>
				<primary_key_column>empresa</primary_key_column>
			</primary_key>
			
			<foreign_keys>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>loja</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>lojas</foreign_table>
				</foreign_key>
			</foreign_keys>
			
			<columns>
				<column> <!-- empresa -->
					<name>empresa</name>
					<internal_attribute>name</internal_attribute>
				</column>
				<column> <!-- loja -->
					<name>loja</name>
					<internal_attribute>child_node[0]</internal_attribute>
				</column>
				
				<column> <!-- morada -->
					<name>morada</name>
					<internal_attribute>name</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- localidade -->
					<name>localidade</name>
					<internal_attribute>zip_code_name</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- codigopos -->
					<name>codipos</name>
					<internal_attribute>zip_code</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>address</name>
					</internal_entity>
				</column>
				<column> <!-- distrito -->
					<name>distrito</name>
					<internal_attribute>province</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				
				<column> <!-- contrib-->
					<name>contrib</name>
					<internal_attribute>corporate_tax_number</internal_attribute>
				</column>
				<column> <!-- natureza-->
					<name>natureza</name>
					<internal_attribute>natureza_juridica</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- capsocial-->
					<name>capsocial</name>
					<internal_attribute>ownership_equity</internal_attribute>
				</column>
				<column> <!-- CAE-->
					<name>cae</name>
					<internal_attribute>cae</internal_attribute>
				</column>
				<column> <!-- iniciact-->
					<name>iniciact</name>
					<internal_attribute>open_date</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_timestamp_to_datetime</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- conserv-->
					<name>conserv</name>
					<internal_attribute>corporate_registration_entity</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- registo-->
					<name>registo</name>
					<internal_attribute>corporate_registration_code</internal_attribute>
				</column>
				
				<column> <!-- logopvd-->
					<name>logopdv</name>
					<internal_attribute>media[0]</internal_attribute>
					<!-- carregar imagem -->
				</column>
				<column> <!-- fundo-->
					<name>fundo</name>
					<internal_attribute>media[1]</internal_attribute>
					<!-- carregar imagem -->
				</column>
				
				<column> <!-- telefone -->
					<name>telefone</name>
					<internal_attribute>phone_number</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- fax -->
					<name>fax</name>
					<internal_attribute>fax_number</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- denomina-->
					<name>denomina</name>
					<internal_attribute>prefered_name</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
			</columns>
		</table>
	</tables>
</input_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/xml/imagens.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = SimÃ£o Rio <srio@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- imagens -->
			<name>imagens</name>
			<internal_entity>media</internal_entity>
			<primary_key>
				<primary_key_column>codigo</primary_key_column>
				<primary_key_column>dirimagem</primary_key_column>
				<primary_key_column>anulado</primary_key_column>
			</primary_key>
			
			<foreign_keys>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>codigo</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>produtos</foreign_table>
				</foreign_key>
			</foreign_keys>
			
			<columns>
				<column> <!-- codigo -->
					<name>codigo</name>
					<internal_attribute>id</internal_attribute>
				</column>
				
				<column> <!-- dirimagem -->
					<name>dirimagem</name>
					<internal_attribute>name</internal_attribute>
				</column>
				
				<column> <!-- anulado -->
					<name>anulado</name>
					<internal_attribute>status</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_diamante_anulado_to_hive_status</name>
						</handler>
					</handlers>
				</column>
			</columns>
		</table>
	</tables>
</input_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/xml/forneced.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (Tue, 21 Oct 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- forneced -->
			<name>forneced</name>
			<internal_entity>supplier</internal_entity>
			<primary_key>
				<primary_key_column>Codigo</primary_key_column>
			</primary_key>
			<foreign_keys>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>Pais</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>paises</foreign_table>
				</foreign_key>
			</foreign_keys>
			<columns>
				<column> <!-- Codigo -->
					<name>Codigo</name>
					<internal_attribute>code</internal_attribute>
				</column>
				<column> <!-- Sobrenome -->
					<name>Sobrenome</name>
					<internal_attribute>surname</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Nome -->
					<name>Nome</name>
					<internal_attribute>name</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Morada -->
					<name>Morada</name>
					<internal_attribute>address</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Tel1 -->
					<name>Tel1</name>
					<internal_attribute>telephone</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Tel2 -->
					<name>Tel2</name>
					<internal_attribute>telephone</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Tel3 -->
					<name>Tel3</name>
					<internal_attribute>telephone</internal_attribute>
					<internal_entity>
						<id>3</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Movel -->
					<name>Movel</name>
					<internal_attribute>mobilePhone</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Fax -->
					<name>Fax</name>
					<internal_attribute>fax</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Email -->
					<name>Email</name>
					<internal_attribute>email</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Url -->
					<name>Url</name>
					<internal_attribute>webPageUrl</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Localidad -->
					<name>Localidad</name>
					<internal_attribute>location</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>					
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Codpos -->
					<name>Codpos</name>
					<internal_attribute>zipCode</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>
				</column>
				<column> <!-- Pais -->
					<name>Pais</name>
					<internal_attribute>country</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>
				</column>
				<column> <!-- Apontament -->
					<name>Apontament</name>
					<internal_attribute>notes</internal_attribute>
				</column>
			</columns>
		</table>
	</tables>
</input_configuration>
