=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/input_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (Tue, 21 Oct 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<xsd:schema targetNamespace="http://www.hive.pt"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.hive.pt">
    <xsd:complexType name="tables">
		<xsd:sequence>
			<xsd:element name="table" type="table" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="table">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1"
				minOccurs="1" />
			<xsd:element name="internal_entity" type="xsd:string"
				maxOccurs="1" minOccurs="1" />
            <xsd:element name="primary_key" type="primary_key" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="foreign_keys" type="foreign_keys" maxOccurs="1" minOccurs="0"></xsd:element>
            <xsd:element name="columns" type="columns" maxOccurs="1" minOccurs="1" />
            <xsd:element name="handlers" type="handlers" maxOccurs="1" minOccurs="0" />
        </xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="primary_key">
		<xsd:sequence>
			<xsd:element name="primary_key_column" type="xsd:string" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="foreign_keys">
		<xsd:sequence>
			<xsd:element name="foreign_key" type="foreign_key" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="foreign_key">
		<xsd:sequence>
            <xsd:element name="foreign_key_columns" type="foreign_key_columns" maxOccurs="1" minOccurs="1" />
            <xsd:element name="foreign_table" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="columns">
		<xsd:sequence>
			<xsd:element name="column" type="column" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="column">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="internal_attribute" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="internal_entity" type="internal_entity" maxOccurs="1" minOccurs="0" />
			<xsd:element name="handlers" type="handlers" maxOccurs="1" minOccurs="0" />
			<xsd:element name="primary_key" type="xsd:boolean" maxOccurs="1" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="handlers">
		<xsd:sequence>
			<xsd:element name="handler" type="handler" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="handler">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="input_configuration">
		<xsd:sequence>
			<xsd:element name="tables" type="tables" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="internal_entity">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:integer" maxOccurs="1" minOccurs="1" />
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="input_configuration" type="input_configuration" />

	<xsd:complexType name="foreign_key_columns">
		<xsd:sequence>
			<xsd:element name="foreign_key_column" type="xsd:string" maxOccurs="unbounded" minOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/xml/tipopaga.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = SimÃ£o Rio <srio@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- tipopaga -->
			<name>tipopaga</name>
			<internal_entity>payment_terms</internal_entity>
			<primary_key>
				<primary_key_column>codigo</primary_key_column>
			</primary_key>
			
			<columns>
				<column> <!-- codigo -->
					<name>codigo</name>
					<internal_attribute>id</internal_attribute>
				</column>
				
				<column> <!-- descricao -->
					<name>descricao</name>
					<internal_attribute>name</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- desconto -->
					<name>desconto</name>
					<internal_attribute>discount</internal_attribute>
				</column>
				<column> <!-- dias -->
					<name>dias</name>
					<internal_attribute>duration_limit</internal_attribute>
				</column>
			</columns>
		</table>
	</tables>
</input_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/input/configuration/diamante_2003/xml/password.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = SimÃ£o Rio <srio@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- passwords -->
			<name>password</name>
			<internal_entity>user</internal_entity>
			<primary_key>
				<primary_key_column>id</primary_key_column>
			</primary_key>
			<foreign_keys>
				<foreign_key>
					<foreign_key_columns>
						<foreign_key_column>vendedor</foreign_key_column>
					</foreign_key_columns>
					<foreign_table>vendedor</foreign_table>
				</foreign_key>
			</foreign_keys>
			<columns>
				<column> <!-- id -->
					<name>id</name>
					<internal_attribute>username</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- chave -->
					<name>chave</name>
					<internal_attribute>password_hash</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_diamante_encryption_to_plaintext</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- actualizou -->
					<name>actualizou</name>
					<internal_attribute>updated_at</internal_attribute>
				</column>
				<column> <!-- grupo -->
					<name>grupo</name>
					<internal_attribute>id</internal_attribute>
					<internal_entity>
						<id>0</id>
						<name>user_group</name>
					</internal_entity>
				</column>
				<column> <!-- vendedor -->
					<name>vendedor</name>
					<internal_attribute>employee</internal_attribute>
				</column>
			</columns>
		</table>
	</tables>
</input_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.adapters.input.handlers/src/colony/plugins/adapters_input_configuration/diamante_2003/xml/clientes.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision$
 __date__      = $LastChangedDate$
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<input_configuration xsi:schemaLocation="http://www.hive.pt ../input_configuration.xsd" xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tables>
		<table> <!-- clientes -->
			<name>clientes</name>
			<internal_entity>customer</internal_entity>
			<columns>
				<column> <!-- Codigo -->
					<name>Codigo</name>
					<primary_key>true</primary_key>
				</column>
				<column> <!-- Nome -->
					<name>Nome</name>
					<internal_attribute>name</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Sobrenome -->
					<name>Sobrenome</name>
					<internal_attribute>surname</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Profissa -->
					<name>Profissa</name>
					<internal_attribute>profession</internal_attribute>
					<referenced_table>profissa</referenced_table>
				</column>
				<column> <!-- Biprop -->
					<name>Biprop</name>
					<internal_attribute>idCardNumber</internal_attribute>
				</column>
				<column> <!-- Contri -->
					<name>Contri</name>
					<internal_attribute>taxNumber</internal_attribute>
				</column>
				<column> <!-- Nib -->
					<name>Nib</name>
					<internal_attribute>bankAccountNumber</internal_attribute>
				</column>
				<column> <!-- Denomina -->
					<name>Denomina</name>
					<internal_attribute>title</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Anos -->
					<name>Anos</name>
					<internal_attribute>birthDate</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_timestamp_to_datetime</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Sexo -->
					<name>Sexo</name>
					<internal_attribute>gender</internal_attribute>
					<handlers>
						<handler>
							<name>column_handler_diamante_gender_id_to_hive_gender_id</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Ext1 -->
					<name>Ext1</name>
					<internal_attribute>telephoneExtension</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Tel1 -->
					<name>Tel1</name>
					<internal_attribute>telephone</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Ext2 -->
					<name>Ext2</name>
					<internal_attribute>telephoneExtension</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Tel2 -->
					<name>Tel2</name>
					<internal_attribute>telephone</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Ext3 -->
					<name>Ext3</name>
					<internal_attribute>telephoneExtension</internal_attribute>
					<internal_entity>
						<id>3</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Tel3 -->
					<name>Tel3</name>
					<internal_attribute>telephone</internal_attribute>
					<internal_entity>
						<id>3</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Movel -->
					<name>Movel</name>
					<internal_attribute>mobilePhone</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Fax -->
					<name>Fax</name>
					<internal_attribute>fax</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
				</column>
				<column> <!-- Email -->
					<name>Email</name>
					<internal_attribute>email</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Url -->
					<name>Url</name>
					<internal_attribute>webPageUrl</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>contact_information</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Pais1 -->
					<name>Pais1</name>
					<internal_attribute>country</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>
					<referenced_table>paises</referenced_table>
				</column>
				<column> <!-- Pais2 -->
					<name>Pais2</name>
					<internal_attribute>country</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>address</name>
					</internal_entity>
					<referenced_table>paises</referenced_table>
				</column>
				<column> <!-- Zona1 -->
					<name>Zona1</name>
					<internal_attribute>zone</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>
					<referenced_table>zonas</referenced_table>
				</column>
				<column> <!-- Zona2 -->
					<name>Zona2</name>
					<internal_attribute>zone</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>address</name>
					</internal_entity>
					<referenced_table>zonas</referenced_table>
				</column>
				<column> <!-- Localidad1 -->
					<name>Localidad1</name>
					<internal_attribute>location</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>					
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Localidad2 -->
					<name>Localidad2</name>
					<internal_attribute>location</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Morada1 -->
					<name>Morada1</name>
					<internal_attribute>address</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Morada2 -->
					<name>Morada2</name>
					<internal_attribute>address</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>address</name>
					</internal_entity>
					<handlers>
						<handler>
							<name>column_handler_string_to_lowercase</name>
						</handler>
					</handlers>
				</column>
				<column> <!-- Codpos1 -->
					<name>Codpos1</name>
					<internal_attribute>zipCode</internal_attribute>
					<internal_entity>
						<id>1</id>
						<name>address</name>
					</internal_entity>
				</column>
				<column> <!-- Codpos2 -->
					<name>Codpos2</name>
					<internal_attribute>zipCode</internal_attribute>
					<internal_entity>
						<id>2</id>
						<name>address</name>
					</internal_entity>
				</column>
				<column> <!--Observ -->
					<name>Observ</name>
					<internal_attribute>observation</internal_attribute>
					<referenced_table>observa</referenced_table>
				</column>
				<column> <!-- Apontament -->
					<name>Apontament</name>
					<internal_attribute>notes</internal_attribute>
				</column>
			</columns>
		</table>

	</tables>
</input_configuration>
