=== hivesolutions/colony-plugins/pt.hive.colony.plugins.system.updater/src/colony/plugins/system_updater/updater/resources/xsd/repositories.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!--
 __author__    = João Magalhães <joamag@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision$
 __date__      = $LastChangedDate$
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<xsd:schema targetNamespace="http://www.hive.pt"
    elementFormDefault="qualified"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.hive.pt">
    <xsd:complexType name="address">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:string" />
            </xsd:extension>
        </xsd:simpleContent>
      </xsd:complexType>
    <xsd:complexType name="addresses">
        <xsd:sequence>
            <xsd:element name="address" type="address" maxOccurs="unbounded" minOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="repository">
        <xsd:all>
            <xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
            <xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="0" />
            <xsd:element name="layout" type="xsd:string" maxOccurs="1" minOccurs="1" />
            <xsd:element name="addresses" type="addresses" maxOccurs="1" minOccurs="1" />
        </xsd:all>
    </xsd:complexType>
    <xsd:complexType name="repositories">
        <xsd:sequence>
            <xsd:element name="repository" type="repository" maxOccurs="unbounded" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="repositories" type="repositories" />
</xsd:schema>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.misc/src/colony/plugins/misc/plugin_downloader/resources/repositories.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = João Magalhães <joamag@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision$
 __date__      = $LastChangedDate$
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<repositories xmlns="http://www.hive.pt"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hive.pt xsd/repositories.xsd">
	<repository>
		<name>Main Repository</name>
		<description>Contains most of the main plugins</description>
		<addresses>
			<address name="Main Address">
				http://latesta.hive/colony/repository
			</address>
			<address name="Chasso Address">
				http://chasso.hive/colony/repository
			</address>
			<address name="Local Address">
				http://localhost/colony/repository
			</address>
			<address name="Example Address">
				http://example.com/colony/repository
			</address>
		</addresses>
	</repository>
	<repository>
		<name>Aux Repository</name>
		<description>
			Contains most of the auxiliary plugins
		</description>
		<addresses>
			<address name="Main Address">
				http://latesta.hive/colony/auxiliary_repository
			</address>
			<address name="Chasso Address">
				http://chasso.hive/colony/auxiliary_repository
			</address>
			<address name="Local Address">
				http://localhost/colony/repository
			</address>
			<address name="Example Address">
				http://example.com/colony/auxiliary_repository
			</address>
		</addresses>
	</repository>
</repositories>
