=== hivesolutions/colony-plugins/pt.hive.colony.plugins.system.updater/src/colony/plugins/system_updater/updater/resources/xsd/repository_descriptor.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = João Magalhães <joamag@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision$
 __date__      = $LastChangedDate$
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<xsd:schema targetNamespace="http://www.hive.pt"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.hive.pt">
	<xsd:complexType name="plugin">
		<xsd:all>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="type" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="id" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="version" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="main_module" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="main_class" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="file_name" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="zip_file" type="xsd:string" maxOccurs="1" minOccurs="0" />
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="plugins">
		<xsd:sequence>
			<xsd:element name="plugin" type="plugin" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="plugin_package">
		<xsd:all>
			<xsd:element name="id" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="version" type="xsd:string" maxOccurs="1" minOccurs="1" />
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="plugins_package">
		<xsd:sequence>
			<xsd:element name="plugin" type="plugin_package" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="package">
		<xsd:all>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="type" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="id" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="version" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="plugins" type="plugins_package" maxOccurs="1" minOccurs="0" />
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="packages">
		<xsd:sequence>
			<xsd:element name="package" type="package" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="repository">
		<xsd:all>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="packages" type="packages" maxOccurs="1" minOccurs="0" />
			<xsd:element name="plugins" type="plugins" maxOccurs="1" minOccurs="0" />
		</xsd:all>
	</xsd:complexType>
	<xsd:element name="repository" type="repository" />
</xsd:schema>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.system.updater/src/colony/plugins/system_updater/updater/resources/schema/repository_descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!--
 __author__    = João Magalhães <joamag@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision$
 __date__      = $LastChangedDate$
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<repository xmlns="http://www.hive.pt"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hive.pt ../xsd/repository_descriptor.xsd">
    <name>Main Repository</name>
    <description>Description</description>
    <layout>simple</layout>
    <packages>
        <package>
            <name></name>
            <type></type>
            <id></id>
            <version></version>
            <plugins>
                <plugin>
                    <id></id>
                    <version></version>
                </plugin>
            </plugins>
        </package>
    </packages>
    <plugins>
        <plugin>
            <name></name>
            <type></type>
            <id></id>
            <version></version>
            <main_module></main_module>
            <main_class></main_class>
            <file_name></file_name>
            <contents_file></contents_file>
        </plugin>
    </plugins>
</repository>
