=== hivesolutions/colony-plugins/pt.hive.colony.plugins.data_converter.configuration.diamante_2003_omni/src/colony/plugins/data_converter_diamante_2003_omni_configuration/adapter/output/configuration/omni/output_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 72 $
 __date__      = $LastChangedDate: 2008-10-21 23:29:54 +0100 (Tue, 21 Oct 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<xsd:schema targetNamespace="http://www.hive.pt" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.hive.pt">
	<xsd:complexType name="output_configuration">
		<xsd:sequence>
			<xsd:element name="domain_entities" type="domain_entities" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="domain_entities">
		<xsd:sequence>
			<xsd:element name="domain_entity" type="domain_entity" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="domain_entity">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="parent" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="table" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="internal_entity" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="attributes" type="attributes" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="attributes">
		<xsd:sequence>
			<xsd:element name="attribute" type="attribute" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="attribute">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="internal_attribute" type="xsd:string" maxOccurs="1" minOccurs="0" />
			<xsd:element name="type" maxOccurs="1" minOccurs="1" type="variable_type" />
            <xsd:element name="primary_key" type="xsd:boolean" maxOccurs="1" minOccurs="0"></xsd:element>
            <xsd:element name="handlers" type="handlers" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="referenced_domain_entity" type="referenced_domain_entity" maxOccurs="unbounded" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="handlers">
		<xsd:sequence>
			<xsd:element name="handler" type="handler" maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="handler">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="referenced_domain_entity">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1" />
			<xsd:element name="multiplicity" type="multiplicity" maxOccurs="1" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="multiplicity">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="one-to-one" />
			<xsd:enumeration value="one-to-many" />
			<xsd:enumeration value="many-to-many" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="output_configuration" type="output_configuration" />
	<xsd:simpleType name="variable_type">
		<xsd:restriction base="xsd:string">
			<xsd:whiteSpace value="collapse" />
			<xsd:pattern value="String\(\d+\)" />
			<xsd:pattern value="Integer" />
			<xsd:pattern value="Date" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.adapters.output.handlers/src/colony/plugins/adapters_output_configuration/hive_2008/xml/Supplier.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision$
 __date__      = $LastChangedDate$
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<output_configuration xsi:schemaLocation="http://www.hive.pt ../output_configuration.xsd"
	xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<domain_entities>
		<domain_entity><!-- Supplier -->
			<name>Supplier</name> 
			<parent>Company</parent>
			<table>suppliers</table>
			<internal_entity>supplier</internal_entity>
			<attributes>
				<attribute><!-- id -->
					<name>id</name>
					<type>Integer</type>
					<primary_key>true</primary_key>
					<referenced_domain_entity>
						<name>Company</name>
						<multiplicity>one-to-one</multiplicity>
					</referenced_domain_entity>
				</attribute>
				<attribute><!-- id -->
					<name>name</name>
					<internal_attribute>name</internal_attribute>
					<type>String(255)</type>
				</attribute>			
			</attributes>
		</domain_entity>
	</domain_entities>
</output_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.adapters.output.handlers/src/colony/plugins/adapters_output_configuration/hive_2008/xml/Person.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision$
 __date__      = $LastChangedDate$
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<output_configuration xsi:schemaLocation="http://www.hive.pt ../output_configuration.xsd"
	xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<domain_entities>
		<domain_entity><!-- Person -->
			<name>Person</name>
			<table>persons</table>
			<attributes>
				<attribute><!-- id -->
					<name>id</name>
					<type>Integer</type>
					<primary_key>true</primary_key>
				</attribute>
				<attribute><!-- name -->
					<name>name</name>
					<internal_attribute>name</internal_attribute>
					<type>String(255)</type>
					<handlers>
						<handler>
							<name>domain_attribute_handler_name</name>
						</handler>
					</handlers>
				</attribute>
				<attribute><!-- title -->
					<name>title</name>
					<internal_attribute>title</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- idCardNumber -->
					<name>idCardNumber</name>
					<internal_attribute>idCardNumber</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- taxNumber -->
					<name>taxNumber</name>
					<internal_attribute>taxNumber</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- bankAccountNumber -->
					<name>bankAccountNumber</name>
					<internal_attribute>bankAccountNumber</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- gender -->
					<name>gender</name>
					<internal_attribute>gender</internal_attribute>
					<type>String(255)</type>
				</attribute>
			</attributes>
		</domain_entity>
	</domain_entities>
</output_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.adapters.output.handlers/src/colony/plugins/adapters_output_configuration/hive_2008/xml/User.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 2101 $
 __date__      = $LastChangedDate: 2008-10-21 13:43:28 +0100 (Ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<output_configuration xsi:schemaLocation="http://www.hive.pt ../output_configuration.xsd"
	xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<domain_entities>
		<domain_entity><!-- User -->
			<name>User</name>
			<table>users</table>
			<internal_entity>user</internal_entity>
			<attributes>
				<attribute><!-- id -->
					<name>id</name>
					<type>Integer</type>
					<primary_key>true</primary_key>
				</attribute>
				<attribute><!-- username -->
					<name>username</name>
					<internal_attribute>id</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- password -->
					<name>password</name>
					<internal_attribute>password</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- passwordMd5 -->
					<name>passwordMd5</name>
					<internal_attribute>password</internal_attribute>
					<type>String(255)</type>
					<handlers>
						<handler>
							<name>domain_attribute_handler_value_to_md5</name>
						</handler>
					</handlers>
				</attribute>
			</attributes>
		</domain_entity>
	</domain_entities>
</output_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.adapters.output.handlers/src/colony/plugins/adapters_output_configuration/hive_2008/xml/Address.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 2101 $
 __date__      = $LastChangedDate: 2008-10-21 13:43:28 +0100 (Ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<output_configuration xsi:schemaLocation="http://www.hive.pt ../output_configuration.xsd"
	xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<domain_entities>
		<domain_entity><!-- Address -->
			<name>Address</name>
			<table>addresses</table>
			<internal_entity>address</internal_entity>
			<attributes>
				<attribute><!-- id -->
					<name>id</name>
					<type>Integer</type>
					<primary_key>true</primary_key>
				</attribute>
				<attribute><!-- country -->
					<name>country</name>
					<internal_attribute>country</internal_attribute>
					<type>String(255)</type>
					<handlers>
						<handler>
							<name>domain_attribute_handler_country</name>
						</handler>
					</handlers>
				</attribute>
				<attribute><!-- district -->
					<name>district</name>
					<internal_attribute>district</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- city -->
					<name>city</name>
					<internal_attribute>city</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- address -->
					<name>address</name>
					<internal_attribute>address</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- zipCode -->
					<name>zipCode</name>
					<internal_attribute>zipCode</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- person -->
					<name>person</name>
					<internal_attribute>customer</internal_attribute>
					<type>Integer</type>
					<referenced_domain_entity>
						<name>Person</name>
						<multiplicity>one-to-one</multiplicity>
					</referenced_domain_entity>
				</attribute>
				<attribute><!-- supplier -->
					<name>company</name>
					<internal_attribute>supplier</internal_attribute>
					<type>Integer</type>
					<referenced_domain_entity>
						<name>Company</name>
						<multiplicity>one-to-one</multiplicity>
					</referenced_domain_entity>
				</attribute>
			</attributes>
		</domain_entity>
	</domain_entities>
</output_configuration>

=== hivesolutions/colony-plugins/pt.hive.colony.plugins.adapters.output.handlers/src/colony/plugins/adapters_output_configuration/hive_2008/xml/ContactInformation.xml
<?xml version="1.0"?>

<!--
 Hive Colony Framework
 Copyright (C) 2008 Hive Solutions Lda.

 This file is part of Hive Colony Framework.

 Hive Colony Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Hive Colony Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Hive Colony Framework. If not, see <http://www.gnu.org/licenses/>.
-->

<!-- 
 __author__    = Tiago Silva <tsilva@hive.pt>
 __version__   = 1.0.0
 __revision__  = $LastChangedRevision: 2101 $
 __date__      = $LastChangedDate: 2008-10-21 13:43:28 +0100 (Ter, 21 Out 2008) $
 __copyright__ = Copyright (c) 2008 Hive Solutions Lda.
 __license__   = GNU General Public License (GPL), Version 3
-->

<output_configuration xsi:schemaLocation="http://www.hive.pt ../output_configuration.xsd"
	xmlns="http://www.hive.pt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<domain_entities>
		<domain_entity><!-- ContactInformation -->
			<name>ContactInformation</name>
			<table>contact_informations</table>
			<internal_entity>contact_information</internal_entity>
			<attributes>
				<attribute><!-- id -->
					<name>id</name>
					<type>Integer</type>
					<primary_key>true</primary_key>
				</attribute>
				<attribute><!-- telephone -->
					<name>telephone</name>
					<internal_attribute>telephone</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- mobilePhone -->
					<name>mobilePhone</name>
					<internal_attribute>mobilePhone</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- fax -->
					<name>fax</name>
					<internal_attribute>fax</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- email -->
					<name>email</name>
					<internal_attribute>email</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- webPageUrl -->
					<name>webPageUrl</name>
					<internal_attribute>webPageUrl</internal_attribute>
					<type>String(255)</type>
				</attribute>
				<attribute><!-- person -->
					<name>person</name>
					<internal_attribute>customer</internal_attribute>
					<type>Integer</type>
					<referenced_domain_entity>
						<name>Person</name>
						<multiplicity>one-to-one</multiplicity>
					</referenced_domain_entity>
				</attribute>
				<attribute><!-- supplier -->
					<name>company</name>
					<internal_attribute>supplier</internal_attribute>
					<type>Integer</type>
					<referenced_domain_entity>
						<name>Company</name>
						<multiplicity>one-to-one</multiplicity>
					</referenced_domain_entity>
				</attribute>
			</attributes>
		</domain_entity>
	</domain_entities>
</output_configuration>
